#!/usr/bin/env python3
"""Render ansible/inventory/aws.yml from Terraform outputs."""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
TF = REPO / "terraform"
OUT = REPO / "ansible" / "inventory" / "aws.yml"
KEY_DEFAULT = Path.home() / ".ssh" / "neo-atari.pem"


def main() -> int:
    raw = subprocess.check_output(
        ["terraform", "output", "-json"], cwd=TF, text=True
    )
    data = json.loads(raw)
    mode = (data.get("mode") or {}).get("value")
    ip = (data.get("public_ip") or {}).get("value")
    if mode != "aws" or not ip:
        print("FAIL: Terraform mode is not aws or public_ip is empty.")
        print("      Run apply with enable_aws=true first.")
        return 1
    key = Path(sys.argv[1]).expanduser() if len(sys.argv) > 1 else KEY_DEFAULT
    text = f"""# Generated by scripts/render_aws_inventory.py — do not edit by hand.
all:
  children:
    mesen_hosts:
      hosts:
        mesen_aws:
          ansible_host: {ip}
          ansible_user: ec2-user
          ansible_ssh_private_key_file: {key}
          ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"
"""
    OUT.write_text(text, encoding="utf-8")
    print(f"PASS: wrote {OUT} for {ip}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
